FROM node AS build

WORKDIR /sobering_madison_ui_garden_build_checks

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx AS production

COPY --from=build /app/build /usr/share/nginx/html
